spring.application.name=projet
server.port=8089

# Database URL with "createDatabaseIfNotExist" flag
spring.datasource.url=jdbc:mysql://localhost:3306/coursdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true